#!/usr/bin/env bash

# bspwm config dir
BSPDIR="$HOME/.config/bspwm"

# forgot what this does
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# fixes java based software
export _JAVA_AWT_WM_NONREPARENTING=1

## AUTOSTART
# killall 'picom'

xrandr --rate 144
xrandr --output DisplayPort-1 --primary --rate 144 
xrandr --output HDMI-A-1 --auto --rate 60 --right-of DisplayPort-1


## MONITORS
bspc monitor DisplayPort-1 -d 1 2 3 4
bspc monitor HDMI-A-1 -d 5 6 7 8

# Set the border colors.
bspc config normal_border_color "#bd16fa"
bspc config active_border_color "#d35cff"
bspc config focused_border_color "#e894ff"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#7018db"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"



CURRENT_BORDER='2.5'
CURRENT_GAP='20'
CURRENT_SRATIO='1.2'

bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

bspc wm --adopt-orphans

bspc rule -r "*"

# kills shume shit
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager polybar

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c /home/bern/.config/sxhkd/sxhkdrc

# launches x settings config
xsettingsd --config="$BSPDIR"/xsettingsd &

# fixez cursor
xsetroot -cursor_name left_ptr

# picom --experimental-backend
polybar main &
polybar secondary &

# start scripts
~/.config/bspwm/polybar/colors
~/.config/bspwm/bspcomp
~/.config/bspwm/bspbar &
~/.config/bspwm/bspdunst
~/.config/bspwm/bspfloat &

feh --bg-fill ~/Pictures/bg.jpg



