#!/usr/bin/env bash

## Startup
# bspwm config dir
BSPDIR="$HOME/.config/bspwm"

# adding bin path
export PATH="$PATH:$HOME/.config/bspwm/bin"

# config path (this does nothing)
# export XDG_CONFIG_HOME="$HOME/.config/bspwm"

# fixes java based software
export _JAVA_AWT_WM_NONREPARENTING=1

# Monitors (yours will be different, obviously)
xrandr --rate 144
xrandr --output DisplayPort-1 --primary --rate 144 
xrandr --output HDMI-A-1 --auto --rate 60 --right-of DisplayPort-1

## BSPC settings
# Desktops config (again, yours will differ)
bspc monitor DisplayPort-1 -d 1 2 3 4
bspc monitor HDMI-A-1 -d 5 6 7 8

# Border colors (this used to be in a different file, but screw that)
# randbg.sh sets this one.
# bspc config normal_border_color "#ef99e2"
# bspc config active_border_color "#cf88bf"
# bspc config focused_border_color "#efc1e0"
# bspc config presel_feedback_color ""

bspc config border_width '0'
bspc config window_gap '2'
bspc config split_ratio '1.2'
bspc config top_padding 16
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

bspc wm --adopt-orphans

# rules
bspc rule -r "*"
bspc rule -a steam desktop=8 focus=off
bspc rule -a dota2 desktop=1
# TF2 starts in a low resolution window. This force resizes it.
bspc rule -a hl2_linux desktop=1 state=floating rectangle=1920x1080+0+0
bspc rule -a discord-screenaudio desktop=5
bspc rule -a steam_proton border=off
bspc rule -a wine border=off

# bspc rule -a Game state=floating
# bspc rule -a Conky sticky=on manage=off lower=on # I don't use conky

## Startup scripts
# kills everything so we don't have double processes
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager polybar bswallow

# shortcut daemon
pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c $HOME/.config/bspwm/sxhkdrc

# window swallow script
pgrep bswallow || bswallow &

# launches xsettings config
xsettingsd --config="$BSPDIR"/xsettingsd &

# cursor fix
xsetroot -cursor_name left_ptr

# screen timeout
xset s noblank
xset s off

# (we start picom in a different script so it doesn't reload when we usr bspc wm -r)
polybar main --config=~/.config/bspwm/polybar/config.ini &
polybar secondary --config=~/.config/bspwm/polybar/config.ini &
~/.config/bspwm/polybar/colors

# notifications
dunst -config ~/.config/bspwm/dunstrc &

